name: Stryker

on:
  push:
    # Argos has to run on your reference branch to creates reference builds
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stryker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
      - name: Run Stryker
        run: cd backend/ && stryker run
      - name: Upload Styrker Report to Sonar Cube
        run: cd reports/mutation/ && jq -f mutation-report-to-sonar.jq mutation.json > mutation-sonar.json
        continue-on-error: true
